#!/bin/bash

set -ex

# Figure out the absolute path of the dotfiles directory
DOTFILESDIRREL="$(dirname "$0")"
cd $DOTFILESDIRREL/..
DOTFILESDIR="$(pwd -P)"

echo "current directory: $DOTFILESDIR"

ln -sf "$DOTFILESDIR/.gitconfig" "$HOME/.gitconfig"

echo "source /usr/share/bash-completion/completions/git" >> "$HOME/.bashrc"

echo "Sourcing bashrc"
source ~/.bashrc
